In [15]:
list_1 = [1,2,3]
print(list_1)

[1, 2, 3]


In [16]:
import numpy as np

In [17]:
numpy_1 = np.array(list_1)
print(numpy_1)

[1 2 3]


In [19]:
zeros_array = np.zeros(5)
print(zeros_array)

[0. 0. 0. 0. 0.]


In [20]:
ones_array = np.ones(5)
print(ones_array)

[1. 1. 1. 1. 1.]


In [21]:
range_array = np.arange(5)
print(range_array)

[0 1 2 3 4]


In [23]:
range_array2 = np.arange(5, 11)
print(range_array2)

[ 5  6  7  8  9 10]


Range 5 is lower bound, 11 is upper boond 

In [24]:
range_array3 = np.arange(0, 15,2)
print(range_array3)

[ 0  2  4  6  8 10 12 14]


In [27]:
linspace_array = np.linspace(0,10,50)
print(linspace_array)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
