In [3]:
import numpy as np

In [4]:
matrix_a = np.matrix([[1,2,3],[3,4,5],[5,6,7]])
print(matrix_a)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [5]:
print(matrix_a[1])

[[3 4 5]]


вторая реализация вывода элементов матрицы

In [33]:
print(matrix_a[1,2])
print(matrix_a[0,2])

5
3


In [35]:
print(matrix_a.size)
print(matrix_a.shape)

9
(3, 3)


In [36]:
print(np.average(matrix_a))

4.0


In [38]:
print(matrix_a.max())
print(matrix_a.min())
print(matrix_a.mean())

7
1
4.0
