In [2]:
import numpy as np

In [3]:
array1 = np.arange(0,11)
print(array1)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [4]:
print(array1[1])

1


In [7]:
print(array1[0])

0


In [29]:
firstFive= array1[5:12]
print(firstFive)

[ 5  6  7  8  9 10]


build a range by two skipping any elements 

In [30]:
lastFive = array1[6::2]
print(lastFive)

[ 6  8 10]


For array which reversed count way need to use negative values on step index 

In [33]:
reverseCount = array1[6:1:-1]
print(reverseCount)

[6 5 4 3 2]


last elements

In [37]:
finalTwo = array1[-3:]
print(finalTwo)

[ 8  9 10]


In [38]:
finalTwo = array1[3:]
print(finalTwo)

[ 3  4  5  6  7  8  9 10]


In [39]:
finalTwo = array1[:3]
print(finalTwo)

[0 1 2]


In [40]:
finalTwo = array1[:-3]
print(finalTwo)

[0 1 2 3 4 5 6 7]


In [43]:
finalTwo = array1[-5:-3]
print(finalTwo)

[6 7]


In [47]:
minarray = min(array1)
print(minarray)

0


In [48]:
arrayMax = max(array1)
print(arrayMax)

10


In [50]:
print(array1.size)

11


In [51]:
print(np.average(array1))

5.0
