In [1]:
list_1 = [1,2,3]

In [2]:
list_1

[1, 2, 3]

In [11]:
list_1

4

In [16]:
for i in range(3):
    list_1 = i
    print(list_1)

0
1
2


In [20]:
import numpy

In [24]:
import numpy

In [28]:
numpy.array(list_1)

array(2)

In [30]:
numpy.arange(1,3)

array([1, 2])

In [31]:
numpy.arange(1,4)

array([1, 2, 3])

In [32]:
list_1 = numpy.arange(1,4)

In [33]:
list_1

array([1, 2, 3])

In [37]:
list_1[1]

2

In [38]:
list_1[0]

1

In [39]:
list_1.size

3

In [41]:
numpy.average(list_1)

2.0

In [42]:
numpy.max(list_1)

3

In [43]:
numpy.min(list_1)

1

In [48]:
numpy.sort(list_1)

array([1, 2, 3])

In [50]:
list_1

array([1, 2, 3])

In [54]:
numpy.append(list_1,10)

array([ 1,  2,  3, 10])

In [55]:
list_1 = list_1+1

In [56]:
list_1

array([2, 3, 4])

In [58]:
numpy.argmax(list_1)

2

In [59]:
numpy.argmin(list_1)

0

In [60]:
list_1 = numpy.add(list_1,100)

In [61]:
list_1

array([102, 103, 104])

In [62]:
matrixArr = numpy.array([[0,0,1,0,0],[0,0,1,0,0]])

In [63]:
matrixArr

array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]])

In [64]:
print(matrixArr[1][2])

1


In [65]:
matrixArr_mod3=numpy.matrix('0,0,1,0,0; 0,0,1,0,0; 0,0,1,0,0')

In [66]:
matrixArr_mod3

matrix([[0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0]])

In [68]:
print(numpy.matrix(numpy.zeros([6,7])))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [69]:
import numpy as np

In [74]:
matrixArr_mod4=np.matrix([[1,2],[3,4]])
print (matrixArr_mod4)

[[1 2]
 [3 4]]


In [75]:
matrixArr_mod4[1,0]=10

In [77]:
print (matrixArr_mod4)

[[ 1  2]
 [10  4]]


In [78]:
matrixArr_mod4[1]=[100,-10]

In [79]:
print (matrixArr_mod4)

[[  1   2]
 [100 -10]]


In [80]:
print (np.sort(matrixArr_mod4))

[[  1   2]
 [-10 100]]


In [81]:
print (-np.sort(-matrixArr_mod4))

[[  2   1]
 [100 -10]]


In [86]:
matrixArr_mod4=np.matrix([[1,2],[3,4]])
print (matrixArr_mod4.T)

[[1 3]
 [2 4]]


In [87]:
print(matrixArr_mod4.flatten())

[[1 2 3 4]]


In [88]:
print(np.add(matrixArr_mod4,matrixArr_mod4))

[[2 4]
 [6 8]]


In [89]:
print(np.matmul(matrixArr_mod4,matrixArr_mod4))

[[ 7 10]
 [15 22]]
