In [1]:
import numpy as np

In [4]:
matrix_picture = np.matrix([[0,0,1,0,0],[1,1,1,1,1],[0,0,1,0,0],[0,0,1,0,0],[0,0,1,0,0]])

In [5]:
print(matrix_picture)

[[0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]]


In [6]:
rows=matrix_picture.shape[0]
columns=matrix_picture.shape[1]
print (rows,columns)

5 5


In [8]:
for row in range(rows):
    for column in range(columns):
        if matrix_picture[row,column] == 0:
            matrix_picture[row,column]=1
        else:
            matrix_picture[row,column] =0
print(matrix_picture)
            
            
            

[[1 1 0 1 1]
 [0 0 0 0 0]
 [1 1 0 1 1]
 [1 1 0 1 1]
 [1 1 0 1 1]]


In [9]:
print(matrix_picture.t)

AttributeError: 'matrix' object has no attribute 't'

In [10]:
print(matrix_picture.T)

[[1 0 1 1 1]
 [1 0 1 1 1]
 [0 0 0 0 0]
 [1 0 1 1 1]
 [1 0 1 1 1]]


In [11]:
print(matrix_picture.flatten)

<bound method matrix.flatten of matrix([[1, 1, 0, 1, 1],
        [0, 0, 0, 0, 0],
        [1, 1, 0, 1, 1],
        [1, 1, 0, 1, 1],
        [1, 1, 0, 1, 1]])>


In [12]:
print(matrix_picture.flatten())

[[1 1 0 1 1 0 0 0 0 0 1 1 0 1 1 1 1 0 1 1 1 1 0 1 1]]
