In [1]:
import numpy as np

In [9]:
array2 = np.arange(0,100,2)
print(array2)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [10]:
array2[0]=1
print(array2)

[ 1  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


Vector Operations


In [20]:
array3 = array2*2
print(array3)
print(array3.size)

[  0   4   8  12  16  20  24  28  32  36  40  44  48  52  56  60  64  68
  72  76  80  84  88  92  96 100 104 108 112 116 120 124 128 132 136 140
 144 148 152 156 160 164 168 172 176 180 184 188 192 196]
50


In [23]:
array2 = np.arange(0,100,2)
array_mod =(np.append(array2,[197,198]))
print(array_mod)
print(array2.size)
print(array_mod.size)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 197 198]
50
52


In [24]:
array_mod2  = (np.insert(array2,1,[3]))
print(array2.size)
print(array_mod2.size)

50
51


In [ ]:
print(np.delete(array2,0))
print(array2.size)

Sorting



In [27]:
anotherArray = np.array([3,6,10,19,20,85,74,38])
print(anotherArray)

[ 3  6 10 19 20 85 74 38]


In [28]:
print(np.sort(anotherArray))

[ 3  6 10 19 20 38 74 85]


In [42]:
print(-np.sort(-anotherArray))

[85 74 38 20 19 10  6  3]
