List of students grades

In [1]:
import numpy as np

In [3]:
studentsArr= np.array([10,50,26,100,99,85,85,85,44,35])
print(studentsArr.size)
print(studentsArr)

10
[ 10  50  26 100  99  85  85  85  44  35]


In [6]:
list_bad_grades = np.amin(studentsArr)
list_cool_grades = np.amax(studentsArr)
list_mean_grades = np.average(studentsArr)


In [21]:
print(list_bad_grades,list_cool_grades,list_mean_grades)
print(np.argmax(studentsArr))
print(np.argmin(studentsArr))

10 100 61.9
3
0


Counter of the unique values

In [19]:
unique, counts = np.unique(studentsArr, return_counts = True)
print(dict(zip(unique, counts)))

{10: 1, 26: 1, 35: 1, 44: 1, 50: 1, 85: 3, 99: 1, 100: 1}


In [23]:
print(np.sort(studentsArr))
print(-np.sort(-studentsArr))

[ 10  26  35  44  50  85  85  85  99 100]
[100  99  85  85  85  50  44  35  26  10]


In [24]:
list_inc_grades = studentsArr*1.2
print(list_inc_grades)

[ 12.   60.   31.2 120.  118.8 102.  102.  102.   52.8  42. ]


Adding elements, a syntactically correct way. NP.Ones gives an example of how to accurately determine the size of an array

In [28]:
studentsAdd = np.add(studentsArr,np.ones(10))
print(studentsAdd)

[ 11.  51.  27. 101. 100.  86.  86.  86.  45.  36.]


In [30]:
studentsAdd = np.add(studentsArr,0)
print(studentsAdd)

[ 10  50  26 100  99  85  85  85  44  35]
