In [2]:
import numpy as  np

In [12]:
matrixArr = np.array([[0,0,1,0,0],[0,0,1,0,0]])
print(matrixArr)
print(matrixArr[1][2])

[[0 0 1 0 0]
 [0 0 1 0 0]]
1


In [13]:
matrixArr_mod=np.matrix([[0,0,1,0,0],[0,0,1,0,0]])
print(matrixArr_mod)

[[0 0 1 0 0]
 [0 0 1 0 0]]


In [17]:
matrixArr_mod2=np.matrix([[0,0,1,0,0],[0,0,1,0,0],[0,0,1,0]])
print(matrixArr_mod2)

[[list([0, 0, 1, 0, 0]) list([0, 0, 1, 0, 0]) list([0, 0, 1, 0])]]


In [4]:
matrixArr_mod3=np.matrix('0,0,1,0,0; 0,0,1,0,0; 0,0,1,0,0')
print(matrixArr_mod3)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]]


In [8]:
print(np.zeros(6))

[0. 0. 0. 0. 0. 0.]


In [16]:
print(np.matrix(np.zeros([6,7])))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [31]:
matrixArr_mod4=np.matrix(np.arange([6,6])))
print(matrixArr_mod4)

SyntaxError: invalid syntax (<ipython-input-31-2bc106dae839>, line 1)